### PR TITLE
[10.x] Test Improvements

### LINKED ISSUE #742: Meilisearch return inconsistent results compared to database/algolia driver when using `take()` + `query()` + `paginate()`
### Scout Version

10.2.2

### Scout Driver

Meilisearch

### Laravel Version

10.12.0

### PHP Version

8.2.6

### Database Driver & Version

MySQL 8.0

### SDK Version

1.1.1

### Meilisearch CLI Version

_No response_

### Description

Given the following use-case:

```php
$queryCallback = fn ($query) => $query->where('created_at', '<', now()->subDays(1));

App\Models\User::search('example')->query($queryCallback)->take(200)->paginate(25);
```

It should search for `"example"` using Scout driver and take only `200` sample size, and from that `200` sample size query using Eloquent with only records created before `24 hours ago` and earlier, paginate the result using `25` records per page.

### Steps To Reproduce

You can refer to the reproducing repository: https://github.com/nova-issues/issue-5574/commit/b666ea2d9d8a96102797ca1b8468d6173281275d

1. Run `composer install`
2. Run `cp .env.example .env`
3. Run `php artisan key:generate`
4. Update Algolia credential on `.env` file.
5. Run `./vendor/bin/sail up -d`
6. Run `./vendor/bin/sail artisan migrate:fresh --seed`
7. Run `./vendor/bin/sail artisan scout:import App\\Models\\UserWithAlgolia`
7. Run `./vendor/bin/sail artisan scout:import App\\Models\\UserWithMeilisearch`
8. Access `/` route from the browser.

image

### PR DESCRIPTION
**Pull request by crynobone**
Clarify expected usage with Database, Algolia and Meilisearch.

Closes #742

### CODE REVIEW

**Comment by crynobone** [comment]
I updated the GitHub Actions to include tests specifically for Meilisearch.

File: tests/Fixtures/User.php [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+     * @return array<string, mixed>
+     */
+    public function toSearchableArray(): array
+    {
+        return [
+            'id' => (int) $this->id,
+            'name' => $this->name,
+        ];
+    }
+}
```
Comment (driesvints) [inline tests/Fixtures/User.php:24]: Should we move this to workbench dir? @crynobone

**Review by driesvints — APPROVED** [review]
Great stuff!
